# ==============================================================================
# STRATEGY_ML.PY - Machine Learning Bot (XGBoost Price Direction Predictor)
# ==============================================================================
import numpy as np
import xgboost as xgb
from sklearn.preprocessing import StandardScaler

# Global model state (trained once, updated periodically)
_model = None
_scaler = None

def _prepare_features(df):
    """Extracts and engineers advanced numerical features for the ML model."""
    df = df.copy()
    
    # Feature 1: BB Squeeze Momentum (distance between bands)
    df["bb_squeeze"] = (df["bb_upper"] - df["bb_lower"]) / df["close"]
    
    # Feature 2: RSI Momentum (change in RSI over last 3 candles)
    df["rsi_mom"] = df["rsi"].diff(3)
    
    # Feature 3: Volume Profile (Volume relative to 20-period moving average)
    df["vol_ma"] = df["volume"].rolling(20).mean()
    df["vol_profile"] = df["volume"] / df["vol_ma"]
    
    # Fill NaN values generated by diff() and rolling()
    df.fillna(0, inplace=True)
    
    features = df[["rsi", "macd", "macd_signal", "macd_hist",
                   "bb_upper", "bb_lower", "atr", "ema_20", "ema_50", 
                   "bb_squeeze", "rsi_mom", "vol_profile"]].copy()
    return features

def _train_model(df):
    """Trains the XGBoost model on historical data."""
    global _model, _scaler

    features = _prepare_features(df[:-1])  # All rows except the last (current) candle

    # Label: 1 if next close > current close, 0 if it goes down
    labels = []
    for i in range(len(df) - 2):
        if df["close"].iloc[i+1] > df["close"].iloc[i]:
            labels.append(1)
        else:
            labels.append(0)

    # Need at least 50 rows to train
    if len(features) < 50 or len(labels) < 50:
        return False

    X = features.iloc[:len(labels)].values
    y = np.array(labels)

    _scaler = StandardScaler()
    X_scaled = _scaler.fit_transform(X)

    # XGBoost configuration
    _model = xgb.XGBClassifier(
        n_estimators=100, 
        max_depth=4, 
        learning_rate=0.1, 
        random_state=42, 
        use_label_encoder=False, 
        eval_metric='logloss'
    )
    _model.fit(X_scaled, y)
    return True

def get_signal(df):
    """
    ML Strategy:
    - Trains an XGBoost model on recent candle data
    - Predicts whether the next candle will go UP or DOWN
    - Places a trade accordingly
    """
    global _model, _scaler

    if df is None or len(df) < 100:
        return None, None, None

    # Train or retrain model every time (in production, you'd cache this)
    trained = _train_model(df)
    if not trained or _model is None:
        return None, None, None

    # Predict on the latest candle
    last_features = _prepare_features(df.tail(1)).values
    last_scaled = _scaler.transform(last_features)
    prediction = _model.predict(last_scaled)[0]
    confidence = _model.predict_proba(last_scaled)[0][prediction]

    # Only trade if confidence is above 65%
    if confidence < 0.65:
        return None, None, None

    last = df.iloc[-1]
    close = last["close"]
    atr = last["atr"]

    if prediction == 1:  # UP
        sl = close - (atr * 1.5)
        tp = close + (atr * 2.5)
        # Using simple print instead of emojis to ensure Windows console compatibility
        print(f"[ML] XGBoost BUY  | Confidence: {confidence:.1%}")
        return "BUY", sl, tp
    else:  # DOWN
        sl = close + (atr * 1.5)
        tp = close - (atr * 2.5)
        print(f"[ML] XGBoost SELL | Confidence: {confidence:.1%}")
        return "SELL", sl, tp
