# quantum/validation/report.py
"""Automated Markdown Report Generator for QUANTUM_BENCHMARK_REPORT.md."""

import datetime
from .benchmark import BenchmarkRunResult

def generate_markdown_report(result: BenchmarkRunResult) -> str:
    now_str = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    audit = result.dataset_audit
    agg = result.aggregate_results
    boots = result.bootstrap_results
    
    lines = []
    lines.append("# QUANTUM BENCHMARK REPORT — WALK-FORWARD PROFITABILITY VALIDATION")
    lines.append("")
    lines.append(f"**Execution Timestamp:** {now_str}  ")
    lines.append(f"**Benchmark Engine:** `quantum/validation`  ")
    lines.append(f"**Benchmark Execution Time:** {result.execution_time_sec:.2f} seconds  ")
    lines.append(f"**Production Trading Authority:** ZERO (RESEARCH / ADVISORY ONLY)  ")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 1. EXECUTIVE SUMMARY & VERDICT")
    lines.append("")
    lines.append(f"```\n================================================================================\nQUANTUM VERDICT: {result.quantum_verdict}\n================================================================================\n```")
    lines.append("")
    lines.append(f"**Verdict Rationale:** {result.verdict_rationale}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 2. DATASET AUDIT & PROVENANCE")
    lines.append("")
    lines.append("| Parameter | Measured Value |")
    lines.append("| :--- | :--- |")
    lines.append(f"| **Symbol** | `{audit.symbol}` |")
    lines.append(f"| **Timeframe** | `{audit.timeframe}` |")
    lines.append(f"| **File Path** | `{audit.file_path}` |")
    lines.append(f"| **Row Count** | {audit.rows} candles |")
    lines.append(f"| **Start Timestamp** | `{audit.start_time}` |")
    lines.append(f"| **End Timestamp** | `{audit.end_time}` |")
    lines.append(f"| **Calendar Span** | {audit.span_days} days |")
    lines.append(f"| **Missing Data Intervals** | {audit.missing_data_intervals} |")
    lines.append(f"| **Duplicate Timestamps** | {audit.duplicate_timestamps} |")
    lines.append(f"| **Sufficient for 90-Day Calendar Splits?** | `{'YES' if audit.is_sufficient_for_90d_wf else 'NO (' + audit.status + ')'}` |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 3. WALK-FORWARD METHODOLOGY")
    lines.append("")
    lines.append(f"The benchmark partitioned historical market data into **{result.n_folds} chronological walk-forward folds**. For each fold:")
    lines.append("1. Feature scaling, parameters, and ML classifiers were fitted **strictly on the Train slice**.")
    lines.append("2. Hyperparameters were checked against the **Validation slice**.")
    lines.append("3. Final execution was evaluated **once on the out-of-sample Test slice**.")
    lines.append("4. Standard Binance fee (0.10%) and execution slippage (0.05%) were applied to all fills.")
    lines.append("")
    lines.append("| Fold | Train Range | Val Range | Test Range | Train Rows | Val Rows | Test Rows |")
    lines.append("| :---: | :--- | :--- | :--- | :---: | :---: | :---: |")
    for f in result.folds:
        lines.append(f"| **Fold {f.fold_idx}** | `{f.train_start[:10]} → {f.train_end[:10]}` | `{f.val_start[:10]} → {f.val_end[:10]}` | `{f.test_start[:10]} → {f.test_end[:10]}` | {f.train_rows} | {f.val_rows} | {f.test_rows} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 4. AGGREGATE PERFORMANCE COMPARISON")
    lines.append("")
    lines.append("| Method | Backend Used | Trades | Win Rate | Profit Factor | Net P&L ($) | Net Return (%) | Max DD (%) | Avg P&L ($) | Total Fees ($) | Latency (ms) |")
    lines.append("| :--- | :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |")
    for s_name, m in agg.items():
        lines.append(f"| **{s_name}** | `{m['backend_used']}` | {m['total_trades']} | {m['win_rate_pct']}% | {m['profit_factor']} | ${m['net_profit']} | {m['net_return_pct']}% | {m['max_drawdown_pct']}% | ${m['avg_trade_pnl']} | ${m['total_fees']} | {m['avg_latency_ms']} ms |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 5. FOLD-BY-FOLD DETAILED BREAKDOWN")
    lines.append("")
    for f in result.folds:
        k = f.fold_idx
        lines.append(f"### Fold {k} (Test Period: `{f.test_start}` to `{f.test_end}`)")
        lines.append("")
        lines.append("| Strategy | Trades | Win Rate | Profit Factor | Net P&L ($) | Net Return (%) | Max DD (%) | Avg Trade ($) | Total Fees ($) |")
        lines.append("| :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |")
        for s_name, res in result.fold_results[k].items():
            lines.append(f"| **{s_name}** | {res.total_trades} | {res.win_rate_pct}% | {res.profit_factor} | ${res.net_profit:.2f} | {res.net_return_pct:.2f}% | {res.max_drawdown_pct:.2f}% | ${res.avg_trade_pnl:.2f} | ${res.total_fees:.2f} |")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 6. BOOTSTRAP STATISTICAL VALIDATION (10,000 RESAMPLES)")
    lines.append("")
    lines.append("Statistical hypothesis testing was conducted using 10,000 bootstrap resamplings of out-of-sample trade return differentials.")
    lines.append("")
    lines.append("| Comparison Hypothesis | Sample Sizes (A vs B) | Mean Difference (%) | 95% Two-Sided CI | Empirical p-value | Entirely Positive? | Significant (p<0.05)? |")
    lines.append("| :--- | :---: | :---: | :---: | :---: | :---: | :---: |")
    for comp_name, b in boots.items():
        lines.append(f"| **{comp_name}** | {b.sample_size_method_a} vs {b.sample_size_method_b} | {b.mean_difference:+.4f}% | `[{b.ci_95_lower:+.4f}%, {b.ci_95_upper:+.4f}%]` | {b.p_value:.4f} | `{'YES' if b.is_entirely_positive else 'NO'}` | `{'YES' if b.is_statistically_significant else 'NO'}` |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 7. SIMULATOR VS. PHYSICAL QUANTUM HARDWARE")
    lines.append("")
    lines.append("* **Physical QPU Hardware Used:** **0.0 seconds** (No real quantum hardware was accessed during this benchmark).")
    lines.append("* **Simulation Infrastructure:** Classical CPU simulation (`Statevector Unitary & Angle Embeddings`).")
    lines.append("* **Distinction:** All metrics reflect classical simulation of shallow quantum circuits; no quantum speedup or physical hardware advantage is claimed.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 8. DATA LEAKAGE AUDIT")
    lines.append("")
    lines.append("1. **Feature Construction:** All technical indicators in `features.py` use strictly backward-looking windows.")
    lines.append("2. **Standardization & Preprocessing:** Scalers (`StandardScaler`) are fit exclusively on the `train_df` of each fold.")
    lines.append("3. **Model Selection & Freezing:** Models are frozen prior to out-of-sample evaluation on `test_df`.")
    lines.append("4. **Anti-Lookahead Verification:** Verified zero usage of future candles (`shift(-1)`) or forward labels.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 9. CONCLUSION")
    lines.append("")
    lines.append(f"**Final Verdict:** **{result.quantum_verdict}**  ")
    lines.append(f"**Operational Status:** **RESEARCH / ADVISORY ONLY**  ")
    lines.append("The quantum research subsystem remains completely isolated from the live/testnet trading execution engine.")
    lines.append("")
    
    return "\n".join(lines)
